# ==========================================
# DEPRECATED: This file is no longer used
# ==========================================
# This project has been migrated to Vercel.
# This file is kept for historical reference only.
# New deployments use vercel.json configuration.
# 
# Migration date: 2025-07-28
# See: .github/workflows/ for current deployment setup
# ==========================================

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = ".next"
  command = "pnpm build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.master.environment]
  BASE_URL = 'https://api.fortress.d.foundation/api/v1'
  GOOGLE_CLIENT_ID = '579303681879-lavu71osb0v5ko9nudn0p2dpppmbqjsb.apps.googleusercontent.com'