import { ROUTES } from './routes'

export enum Permission {
  AUTH_READ = 'auth.read',
  EMPLOYEES_READ = 'employees.read',
  EMPLOYEES_CREATE = 'employees.create',
  EMPLOYEES_EDIT = 'employees.edit',
  EMPLOYEES_DELETE = 'employees.delete',
  PROJECTS_CREATE = 'projects.create',
  PROJECTS_READ = 'projects.read',
  PROJECTS_EDIT = 'projects.edit',
  PROJECTMEMBERS_CREATE = 'projectMembers.create',
  PROJECTMEMBERS_READ = 'projectMembers.read',
  PROJECTMEMBERS_EDIT = 'projectMembers.edit',
  PROJECTMEMBERS_DELETE = 'projectMembers.delete',
  PROJECTWORKUNITS_CREATE = 'projectWorkUnits.create',
  PROJECTWORKUNITS_READ = 'projectWorkUnits.read',
  PROJECTWORKUNITS_EDIT = 'projectWorkUnits.edit',
  PROJECTWORKUNITS_DELETE = 'projectWorkUnits.delete',
  FEEDBACKS_CREATE = 'feedbacks.create',
  FEEDBACKS_READ = 'feedbacks.read',
  FEEDBACKS_EDIT = 'feedbacks.edit',
  FEEDBACKS_DELETE = 'feedbacks.delete',
  EMPLOYEEEVENTQUESTIONS_CREATE = 'employeeEventQuestions.create',
  EMPLOYEEEVENTQUESTIONS_EDIT = 'employeeEventQuestions.edit',
  EMPLOYEEEVENTQUESTIONS_READ = 'employeeEventQuestions.read',
  EMPLOYEEEVENTQUESTIONS_DELETE = 'employeeEventQuestions.delete',
  SURVEYS_CREATE = 'surveys.create',
  SURVEYS_READ = 'surveys.read',
  SURVEYS_EDIT = 'surveys.edit',
  SURVEYS_DELETE = 'surveys.delete',
}

export const pagePermissions = {
  [ROUTES.EMPLOYEES]: Permission.EMPLOYEES_READ,
  [ROUTES.EMPLOYEE_DETAIL('[id]')]: Permission.EMPLOYEES_READ,
  [ROUTES.ADD_EMPLOYEE]: Permission.EMPLOYEES_CREATE,
  [ROUTES.PROJECTS]: Permission.PROJECTS_READ,
  [ROUTES.PROJECT_DETAIL('[id]')]: Permission.PROJECTS_READ,
  [ROUTES.ADD_PROJECT]: Permission.PROJECTS_CREATE,
}
