import { ROUTES } from './routes'

export enum Permission {
  AUTH_READ = 'auth.read',
  EMPLOYEEEVENTQUESTIONS_CREATE = 'employeeEventQuestions.create',
  EMPLOYEEEVENTQUESTIONS_DELETE = 'employeeEventQuestions.delete',
  EMPLOYEEEVENTQUESTIONS_EDIT = 'employeeEventQuestions.edit',
  EMPLOYEEEVENTQUESTIONS_READ = 'employeeEventQuestions.read',
  EMPLOYEEMENTEES_CREATE = 'employeeMentees.create',
  EMPLOYEEMENTEES_DELETE = 'employeeMentees.delete',
  EMPLOYEEMENTEES_EDIT = 'employeeMentees.edit',
  EMPLOYEEMENTEES_READ = 'employeeMentees.read',
  EMPLOYEEROLES_CREATE = 'employeeRoles.create',
  EMPLOYEEROLES_DELETE = 'employeeRoles.delete',
  EMPLOYEEROLES_EDIT = 'employeeRoles.edit',
  EMPLOYEEROLES_READ = 'employeeRoles.read',
  EMPLOYEES_CREATE = 'employees.create',
  EMPLOYEES_DELETE = 'employees.delete',
  EMPLOYEES_EDIT = 'employees.edit',
  EMPLOYEES_READ = 'employees.read',
  EMPLOYEES_READ_FULLACCESS = 'employees.read.fullAccess',
  EMPLOYEES_READ_FILTERBYALLSTATUSES = 'employees.read.filterByAllStatuses',
  EMPLOYEES_READ_FILTERBYPROJECT = 'employees.read.filterByProject',
  EMPLOYEES_READ_GENERALINFO_FULLACCESS = 'employees.read.generalInfo.fullAccess',
  EMPLOYEES_READ_PERSONALINFO_FULLACCESS = 'employees.read.personalInfo.fullAccess',
  EMPLOYEES_READ_PROJECTS_FULLACCESS = 'employees.read.projects.fullAccess',
  EMPLOYEES_READ_PROJECTS_READACTIVE = 'employees.read.projects.readActive',
  FEEDBACKS_CREATE = 'feedbacks.create',
  FEEDBACKS_DELETE = 'feedbacks.delete',
  FEEDBACKS_EDIT = 'feedbacks.edit',
  FEEDBACKS_READ = 'feedbacks.read',
  METADATA_CREATE = 'metadata.create',
  METADATA_DELETE = 'metadata.delete',
  METADATA_EDIT = 'metadata.edit',
  METADATA_READ = 'metadata.read',
  PROJECTMEMBERS_CREATE = 'projectMembers.create',
  PROJECTMEMBERS_DELETE = 'projectMembers.delete',
  PROJECTMEMBERS_EDIT = 'projectMembers.edit',
  PROJECTMEMBERS_READ = 'projectMembers.read',
  PROJECTS_CREATE = 'projects.create',
  PROJECTS_EDIT = 'projects.edit',
  PROJECTS_READ = 'projects.read',
  PROJECTS_READ_FULLACCESS = 'projects.read.fullAccess',
  PROJECTWORKUNITS_CREATE = 'projectWorkUnits.create',
  PROJECTWORKUNITS_CREATE_FULLACCESS = 'projectWorkUnits.create.fullAccess',
  PROJECTWORKUNITS_DELETE = 'projectWorkUnits.delete',
  PROJECTWORKUNITS_DELETE_FULLACCESS = 'projectWorkUnits.delete.fullAccess',
  PROJECTWORKUNITS_EDIT = 'projectWorkUnits.edit',
  PROJECTWORKUNITS_EDIT_FULLACCESS = 'projectWorkUnits.edit.fullAccess',
  PROJECTWORKUNITS_READ = 'projectWorkUnits.read',
  PROJECTWORKUNITS_READ_FULLACCESS = 'projectWorkUnits.read.fullAccess',
  SURVEYS_CREATE = 'surveys.create',
  SURVEYS_DELETE = 'surveys.delete',
  SURVEYS_EDIT = 'surveys.edit',
  SURVEYS_READ = 'surveys.read',
  DASHBOARDS_READ = 'dashboards.read',
  DASHBOARDS_PROJECTS_READ = 'dashboards.projects.read',
  DASHBOARDS_RESOURCES_READ = 'dashboards.resources.read',
  DASHBOARDS_ENGAGEMENT_READ = 'dashboards.engagement.read',
  INVOICES_READ = 'invoices.read',
  INVOICES_CREATE = 'invoices.create',
  PROJECTS_COMMISSIONRATE_READ = 'projects.commissionRate.read',
  PROJECTS_COMMISSIONRATE_EDIT = 'projects.commissionRate.edit',
}

// the permission that needs to access to a certain page
export const pagePermissions = {
  [ROUTES.EMPLOYEES]: Permission.EMPLOYEES_READ,
  [ROUTES.EMPLOYEE_DETAIL('[id]')]: Permission.EMPLOYEES_READ,
  [ROUTES.ADD_EMPLOYEE]: Permission.EMPLOYEES_CREATE,
  [ROUTES.PROJECTS]: Permission.PROJECTS_READ,
  [ROUTES.PROJECT_DETAIL('[id]')]: Permission.PROJECTS_READ,
  [ROUTES.ADD_PROJECT]: Permission.PROJECTS_CREATE,
  [ROUTES.INBOX]: Permission.FEEDBACKS_READ,
  [ROUTES.FEEDBACK_INBOX_DETAIL('[id]')]: Permission.FEEDBACKS_READ,
  [ROUTES.PEER_REVIEW]: Permission.SURVEYS_READ,
  [ROUTES.PEER_REVIEW_EVENT_DETAIL('[id]')]: Permission.SURVEYS_READ,
  [ROUTES.EMPLOYEE_PEER_REVIEWS('[id]', '[topicId]')]: Permission.SURVEYS_READ,
  [ROUTES.ENGAGEMENT]: Permission.SURVEYS_READ,
  [ROUTES.EMPLOYEE_ENGAGEMENT_DETAIL('[id]')]: Permission.SURVEYS_READ,
  [ROUTES.WORK]: Permission.SURVEYS_READ,
  [ROUTES.WORK_DETAIL('[id]')]: Permission.SURVEYS_READ,
  [ROUTES.DASHBOARD]: Permission.DASHBOARDS_READ,
  [ROUTES.INVOICES]: Permission.INVOICES_READ,
}
