export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  PROJECTS: '/projects',
  ADD_PROJECT: '/projects/new',
  PROJECT_DETAIL: (id: string) => `/projects/${id}`,
  EDIT_PROJECT: (id: string) => `/projects/${id}/edit`,
  CREATE_PROJECT: `/projects/new`,
  EMPLOYEES: '/employees',
  ADD_EMPLOYEE: '/employees/new',
  EMPLOYEE_DETAIL: (id: string) => `/employees/${id}`,
  EDIT_EMPLOYEE: (id: string) => `/employees/${id}/edit`,
  FEEDBACKS: '/feedbacks',
  CONFIG: '/config',
  PROFILE: '/profile',
}
